# Generated by Django 4.2 on 2026-08-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_number', models.CharField(db_index=True, help_text='Unique product identifier / SKU', max_length=255, unique=True)),
                ('model_number', models.CharField(blank=True, db_index=True, help_text='Product model number', max_length=255, null=True)),
                ('product_category', models.CharField(blank=True, db_index=True, help_text='Raw source product category', max_length=255, null=True)),
                ('product_sub_category', models.CharField(blank=True, db_index=True, help_text='Raw source product sub-category', max_length=255, null=True)),
                ('collection_name', models.CharField(blank=True, help_text='Collection or line name', max_length=255, null=True)),
                ('color_collection', models.CharField(blank=True, help_text='Color collection family', max_length=255, null=True)),
                ('product_color', models.CharField(blank=True, help_text='Specific product color / finish', max_length=255, null=True)),
                ('product_name', models.CharField(blank=True, db_index=True, help_text='Product title / name', max_length=500, null=True)),
                ('brand', models.CharField(blank=True, db_index=True, help_text='Brand, vendor, or manufacturer name', max_length=255, null=True)),
                ('product_description', models.TextField(blank=True, help_text='Detailed marketing description', null=True)),
                ('bullets', models.TextField(blank=True, help_text='Feature bullet points', null=True)),
                ('set_includes', models.TextField(blank=True, help_text='Set inclusions / contents description', null=True)),
                ('product_weight', models.CharField(blank=True, help_text="Product weight (e.g. '105')", max_length=100, null=True)),
                ('materials', models.TextField(blank=True, help_text='Materials & construction details', null=True)),
                ('product_dimensions', models.TextField(blank=True, help_text='Product dimensions & measurements', null=True)),
                ('assembly_required', models.CharField(blank=True, help_text='Assembly required indicator (Y/N)', max_length=50, null=True)),
                ('is_set', models.CharField(blank=True, help_text='Is a set indicator (Y/N)', max_length=50, null=True)),
                ('stackable', models.CharField(blank=True, help_text='Stackable indicator (Y/N)', max_length=50, null=True)),
                ('country_of_origin', models.CharField(blank=True, help_text='Country of origin / manufacturing', max_length=100, null=True)),
                ('item_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Wholesale item cost', max_digits=12, null=True)),
                ('map_price', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum Advertised Price (MAP)', max_digits=12, null=True)),
                ('msrp', models.DecimalField(blank=True, decimal_places=2, help_text='Manufacturer Suggested Retail Price (MSRP)', max_digits=12, null=True)),
                ('images', models.JSONField(blank=True, default=list, help_text='List of up to 20 image URLs')),
                ('shipping_method', models.CharField(blank=True, help_text='Shipping method / freight type', max_length=100, null=True)),
                ('total_box_count', models.CharField(blank=True, help_text='Total number of shipping boxes', max_length=50, null=True)),
                ('pallet_count', models.CharField(blank=True, help_text='Pallet count', max_length=50, null=True)),
                ('shipping_weight', models.CharField(blank=True, help_text='Total shipping weight', max_length=100, null=True)),
                ('total_cbm', models.CharField(blank=True, help_text='Total cubic meters (CBM)', max_length=100, null=True)),
                ('package_dimensions', models.TextField(blank=True, help_text='Package / carton dimensions', null=True)),
                ('product_url', models.CharField(blank=True, help_text='Source product URL', max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'catalog_product',
                'ordering': ['product_number'],
            },
        ),
    ]
