# Generated by Django 4.2 on 2026-08-17 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', help_text='Job execution status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('total_products', models.PositiveIntegerField(default=0, help_text='Total number of products queued in this job')),
                ('processed_count', models.PositiveIntegerField(default=0, help_text='Number of products processed so far')),
                ('failed_count', models.PositiveIntegerField(default=0, help_text='Number of products that encountered errors during classification')),
            ],
            options={
                'verbose_name': 'Classification Job',
                'verbose_name_plural': 'Classification Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField(db_index=True, default=0.0, help_text='Prediction confidence score (0.0 to 1.0)')),
                ('alternative_categories', models.JSONField(blank=True, default=list, help_text='Alternative top-K predicted categories: list of {category_id, name, score}')),
                ('extracted_attributes', models.JSONField(blank=True, default=dict, help_text='Extracted attributes dictionary: {attribute_name: {value, confidence}}')),
                ('needs_manual_review', models.BooleanField(db_index=True, default=False, help_text='Flag indicating confidence is below threshold or ambiguity requires human review')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='pending', help_text='Result processing state', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error details if classification failed', null=True)),
                ('reviewed_by', models.CharField(blank=True, help_text='Username of human reviewer who inspected/approved this result', max_length=150, null=True)),
                ('approved', models.BooleanField(db_index=True, default=False, help_text='Whether this classification is approved for export')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(help_text='Classification job run', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='classification.classificationjob')),
                ('predicted_category', models.ForeignKey(blank=True, help_text='Primary predicted Shopify taxonomy category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classification_predictions', to='taxonomy.category')),
                ('product', models.ForeignKey(help_text='Product that was classified', on_delete=django.db.models.deletion.CASCADE, related_name='classification_results', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Classification Result',
                'verbose_name_plural': 'Classification Results',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='classificationresult',
            index=models.Index(fields=['needs_manual_review', 'status'], name='idx_review_status'),
        ),
        migrations.AddIndex(
            model_name='classificationresult',
            index=models.Index(fields=['job', 'status'], name='idx_job_status'),
        ),
        migrations.AddConstraint(
            model_name='classificationresult',
            constraint=models.UniqueConstraint(fields=('product', 'job'), name='unique_product_job_result'),
        ),
    ]
