# Generated by Django 4.2 on 2026-08-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', help_text='Job execution status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('total_products', models.PositiveIntegerField(default=0, help_text='Total number of products queued in this job')),
                ('processed_count', models.PositiveIntegerField(default=0, help_text='Number of products processed so far')),
                ('failed_count', models.PositiveIntegerField(default=0, help_text='Number of products that encountered errors during classification')),
            ],
            options={
                'verbose_name': 'Classification Job',
                'verbose_name_plural': 'Classification Jobs',
                'db_table': 'classification_classificationjob',
                'ordering': ['-created_at'],
            },
        ),
    ]
