# Generated by Django 4.2 on 2026-08-20 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.CharField(help_text='Shopify taxonomy attribute GID (e.g. gid://shopify/TaxonomyAttribute/1) or identifier', max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text='Attribute name (e.g. Color, Sleeve Length)', max_length=255)),
            ],
            options={
                'verbose_name': 'Attribute',
                'verbose_name_plural': 'Attributes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(help_text='Shopify taxonomy GID (e.g. gid://shopify/TaxonomyCategory/aa-1) or identifier', max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text='Category local name (e.g. Shirts)', max_length=255)),
                ('full_name', models.CharField(db_index=True, help_text='Full category breadcrumb path (e.g. Apparel & Accessories > Clothing > Tops > Shirts)', max_length=500)),
                ('level', models.PositiveIntegerField(db_index=True, default=0, help_text='Depth level in taxonomy hierarchy (0 = Root)')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent category in the taxonomy tree', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='taxonomy.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.CharField(help_text='Shopify taxonomy attribute value GID (e.g. gid://shopify/TaxonomyValue/1) or identifier', max_length=255, primary_key=True, serialize=False)),
                ('value', models.CharField(db_index=True, help_text='The value string (e.g. Red, XL, Cotton)', max_length=255)),
                ('attribute', models.ForeignKey(help_text='The attribute this value belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='values', to='taxonomy.attribute')),
            ],
            options={
                'verbose_name': 'Attribute Value',
                'verbose_name_plural': 'Attribute Values',
                'ordering': ['attribute', 'value'],
            },
        ),
        migrations.AddField(
            model_name='attribute',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Categories to which this attribute applies', related_name='attributes', to='taxonomy.category'),
        ),
    ]
