# Generated by Django 4.2 on 2026-08-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(help_text='Original uploaded filename', max_length=255)),
                ('sheet_name', models.CharField(blank=True, help_text='Sheet name or index', max_length=100, null=True)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('imported_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('partial', 'Partial Success'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('data_quality_metrics', models.JSONField(blank=True, default=dict, help_text='Data quality stats (missing descriptions, images, prices)')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Catalog Import',
                'verbose_name_plural': 'Catalog Imports',
                'ordering': ['-created_at'],
            },
        ),
    ]
